version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: flightdb
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: my_password
    ports:
      - "3308:3306"   # Maps host port 3308 to container port 3306
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: